db_url: sqlite:///data/finstat.db
input_folder: input
archive_folder: archive
filename_regex: (?P<bank_id>[A-Za-z0-9_-]+)_(?P<form>[A-Za-z0-9_-]+)_(?P<date>(\d{8}|\d{4}-\d{2}-\d{2}))\.dbf
default_item_fields:
- ITEM
- ROW_CODE
- CODE
- ACODE
- STR
- C1
default_value_fields:
- VALUE
- AMOUNT
- SUM
- VAL
- VSEGO
- C3
- IITG
forms:
  0409101:
    item_field: NUM_SC
    value_field: IITG
    bank_field: REGN
    encoding: cp866
    filename_patterns:
    - (?P<mm>\d{2})(?P<yyyy>\d{4})B1\.dbf
    ap_field: A_P
    ap_map:
      '1': A
      '2': P
      '3': AP
  0409102:
    item_field: CODE
    value_field: SIM_ITOGO
    bank_field: REGN
    encoding: cp866
    filename_patterns:
    - (?P<mm>\d{2})(?P<yyyy>\d{4})_P1\.dbf
    - Q(?P<q>\d)(?P<yyyy>\d{4})_P1\.dbf
  0409802:
    item_field: STR
    value_field: VSEGO
    bank_field: REGN_GKO
    encoding: cp866
    filename_patterns:
    - PK802(?P<yy>\d{2})(?P<mm>\d{2})\.dbf
  0409803:
    item_field: STR
    value_field: VSEGO
    bank_field: REGN_GKO
    encoding: cp866
    filename_patterns:
    - PK803(?P<yy>\d{2})(?P<mm>\d{2})\.dbf
  0409805:
    item_field: NAME_NORM
    value_field: FAKT_ZN
    bank_field: REGN_GKO
    encoding: cp866
    filename_patterns:
    - PN805(?P<yy>\d{2})(?P<mm>\d{2})\.dbf
  0409123:
    item_field: C1
    value_field: C3
    bank_field: REGN
    encoding: cp866
    filename_patterns:
    - (?P<mm>\d{2})(?P<yyyy>\d{4})_123D\.dbf
  0409135_3:
    item_field: C1_3
    value_field: C2_3
    bank_field: REGN
    encoding: cp866
    filename_patterns:
    - (?P<mm>\d{2})(?P<yyyy>\d{4})_135_3\.dbf
llm:
  provider: gigachat
  mode: responses
  model: gpt-5
  reasoning_effort: low
  system_prompt_file: configs/llm_system_prompt.txt
  user_prompt_file: configs/llm_user_prompt.txt
  bank_limit: 0
  max_banks: 0
  only_errors: false
  dry_run: false
  strict_cache: false
  timeout_sec: 180
  max_retries: 2
  backoff_seconds: 2
  stop_after_consecutive_errors: 10
  concurrency: 1
  retry_policy:
    max_retries: 2
    backoff_seconds: 2
  gigachat:
    model: GigaChat-2-Max
    base_url: https://sbercode.atdcode.ru/proxy/api/v1/gigachat/
    scope: GIGACHAT_API_PERS
    timeout_sec: 180
    temperature: 0.1
    top_p: 0.3
    max_tokens: 2000
    profanity_check: false
    verify_ssl_certs: false
