QN1:
  name: "Совокупный процентный и дивидендный доход"
  description: "Сумма процентных и дивидендных доходов за период"
QN2:
  name: "Совокупные процентные расходы"
  description: "Сумма процентных расходов по обязательствам"
A1:
  name: "Денежные средства/ликвидные активы"
  description: "Касса, счета в ЦБ и высоколиквидные активы."
QN9:
  name: "Кредиты клиентам (net)"
  description: "Совокупный кредитный портфель за вычетом резервов."
O1:
  name: "Средства клиентов"
  description: "Фондирование от клиентов; устойчивость пассивов."
O2:
  name: "Средства банков"
  description: "Зависимость от межбанковского фондирования."
QN11:
  name: "Проблемные кредиты (NPL)"
  description: "Рост указывает на ухудшение качества активов."
QN15:
  name: "Совокупный капитал"
  description: "Капитальная база банка."
QN18:
  name: "H1.0 — достаточность совокупного капитала"
  description: "Регуляторный норматив достаточности капитала."
QN19:
  name: "H1.2 — достаточность капитала 1-го уровня"
  description: "Ключевой показатель качества капитала."
QN13:
  name: "Совокупные активы"
  description: "Размер баланса, база для масштабирования."
QN17:
  name: "Межбанковский коэффициент"
  description: "Баланс межбанковских позиций; рост — повышенная зависимость от МБК."
QN16:
  name: "ROAA"
  description: "Рентабельность активов."

# Производные метрики: изменение за 1 и 6 месяцев (%) для показателей, которые передаются в LLM
A1_PCT_M1:
  name: "Изменение Денежные средства/ликвидные активы за 1 месяц, %"
  description: "Процентное изменение значения A1 относительно уровня месяц назад."
A1_PCT_M6:
  name: "Изменение Денежные средства/ликвидные активы за 6 месяцев, %"
  description: "Процентное изменение значения A1 относительно уровня шесть месяцев назад (гибкое окно)."

QN9_PCT_M1:
  name: "Изменение Кредиты клиентам (net) за 1 месяц, %"
  description: "Процентное изменение значения QN9 относительно уровня месяц назад."
QN9_PCT_M6:
  name: "Изменение Кредиты клиентам (net) за 6 месяцев, %"
  description: "Процентное изменение значения QN9 относительно уровня шесть месяцев назад (гибкое окно)."

O1_PCT_M1:
  name: "Изменение Средства клиентов за 1 месяц, %"
  description: "Процентное изменение значения O1 относительно уровня месяц назад."
O1_PCT_M6:
  name: "Изменение Средства клиентов за 6 месяцев, %"
  description: "Процентное изменение значения O1 относительно уровня шесть месяцев назад (гибкое окно)."

O2_PCT_M1:
  name: "Изменение Средства банков за 1 месяц, %"
  description: "Процентное изменение значения O2 относительно уровня месяц назад."
O2_PCT_M6:
  name: "Изменение Средства банков за 6 месяцев, %"
  description: "Процентное изменение значения O2 относительно уровня шесть месяцев назад (гибкое окно)."

QN11_PCT_M1:
  name: "Изменение Проблемные кредиты (NPL) за 1 месяц, %"
  description: "Процентное изменение значения QN11 относительно уровня месяц назад."
QN11_PCT_M6:
  name: "Изменение Проблемные кредиты (NPL) за 6 месяцев, %"
  description: "Процентное изменение значения QN11 относительно уровня шесть месяцев назад (гибкое окно)."

QN15_PCT_M1:
  name: "Изменение Совокупный капитал за 1 месяц, %"
  description: "Процентное изменение значения QN15 относительно уровня месяц назад."
QN15_PCT_M6:
  name: "Изменение Совокупный капитал за 6 месяцев, %"
  description: "Процентное изменение значения QN15 относительно уровня шесть месяцев назад (гибкое окно)."

QN18_PCT_M1:
  name: "Изменение H1.0 — достаточность совокупного капитала за 1 месяц, %"
  description: "Процентное изменение значения QN18 относительно уровня месяц назад."
QN18_PCT_M6:
  name: "Изменение H1.0 — достаточность совокупного капитала за 6 месяцев, %"
  description: "Процентное изменение значения QN18 относительно уровня шесть месяцев назад (гибкое окно)."

QN19_PCT_M1:
  name: "Изменение H1.2 — достаточность капитала 1-го уровня за 1 месяц, %"
  description: "Процентное изменение значения QN19 относительно уровня месяц назад."
QN19_PCT_M6:
  name: "Изменение H1.2 — достаточность капитала 1-го уровня за 6 месяцев, %"
  description: "Процентное изменение значения QN19 относительно уровня шесть месяцев назад (гибкое окно)."

QN13_PCT_M1:
  name: "Изменение Совокупные активы за 1 месяц, %"
  description: "Процентное изменение значения QN13 относительно уровня месяц назад."
QN13_PCT_M6:
  name: "Изменение Совокупные активы за 6 месяцев, %"
  description: "Процентное изменение значения QN13 относительно уровня шесть месяцев назад (гибкое окно)."
