# Одиночные пороги отключены — используются только наборы yellow_sets / red_sets

# Группа условий (все вместе, логика AND) для статуса Yellow
yellow_sets:
  # Набор 1 (все условия должны выполниться)
  - QN9_PCT_M1: "< -5"     # кредитный портфель: уменьшение >5% за месяц
    QN9_PCT_M6: "< -10"    # кредитный портфель: уменьшение >10% за полгода
    O1_PCT_M1: "< -5"      # счета клиентов: уменьшение >5% за месяц
    O1_PCT_M6: "< -10"     # счета клиентов: уменьшение >10% за полгода
    QN15_PCT_M1: "< -5"    # совокупный капитал: уменьшение >5% за месяц
    QN15_PCT_M6: "< -10"   # совокупный капитал: уменьшение >10% за полгода
    QN18_PCT_M1: "< -5"    # H1.0: уменьшение >5% за месяц
    QN18_PCT_M6: "< -10"   # H1.0: уменьшение >10% за полгода
    QN19_PCT_M1: "< -5"    # H1.2: уменьшение >5% за месяц
    QN19_PCT_M6: "< -10"   # H1.2: уменьшение >10% за полгода
  # Набор 2 (все условия должны выполниться)
  - QN11_PCT_M1: "> 5"     # рост проблемных кредитов >5% за месяц
    QN11_PCT_M6: "> 10"    # рост проблемных кредитов >10% за полгода
    QN9_PCT_M1:  "< -5"    # снижение кредитного портфеля >5% за месяц
    QN9_PCT_M6:  "< -10"   # снижение кредитного портфеля >10% за полгода
    O2_PCT_M1:   "> 5"     # рост средств, привлечённых от банков >5% за месяц
    O2_PCT_M6:   "> 10"    # рост средств, привлечённых от банков >10% за полгода
    O1_PCT_M1:   "< -5"    # снижение счетов клиентов >5% за месяц
    O1_PCT_M6:   "< -10"   # снижение счетов клиентов >10% за полгода
  # Набор 3 (все условия должны выполниться)
  - QN13_PCT_M1: "< -5"    # снижение совокупных активов >5% за месяц
    QN13_PCT_M6: "< -10"   # снижение совокупных активов >10% за полгода
    A1_PCT_M1:   "< -5"    # снижение денежных средств >5% за месяц
    A1_PCT_M6:   "< -10"   # снижение денежных средств >10% за полгода
    QN9_PCT_M1:  "< -5"    # снижение кредитного портфеля >5% за месяц
    QN9_PCT_M6:  "< -10"   # снижение кредитного портфеля >10% за полгода
    O1_PCT_M1:   "< -5"    # снижение счетов клиентов >5% за месяц
    O1_PCT_M6:   "< -10"   # снижение счетов клиентов >10% за полгода

# Пороги для статуса Red как AND-набор: ВСЕ условия должны выполниться
red_and:
  QN9_PCT_M1:  "< -10"   # кредитный портфель ↓ >10% за месяц
  QN9_PCT_M6:  "< -20"   # кредитный портфель ↓ >20% за полгода
  O1_PCT_M1:   "< -10"   # счета клиентов ↓ >10% за месяц
  O1_PCT_M6:   "< -20"   # счета клиентов ↓ >20% за полгода
  QN15_PCT_M1: "< -10"   # капитал ↓ >10% за месяц
  QN15_PCT_M6: "< -20"   # капитал ↓ >20% за полгода
  QN18_PCT_M1: "< -10"   # H1.0 ↓ >10% за месяц
  QN18_PCT_M6: "< -20"   # H1.0 ↓ >20% за полгода
  QN19_PCT_M1: "< -10"   # H1.2 ↓ >10% за месяц
  QN19_PCT_M6: "< -20"   # H1.2 ↓ >20% за полгода

# Дополнительные Red-наборы (AND внутри, OR между наборами)
red_sets:
  # Набор 2
  - QN11_PCT_M1: "> 10"   # проблемные кредиты ↑ >10% за месяц
    QN11_PCT_M6: "> 20"   # проблемные кредиты ↑ >20% за полгода
    QN9_PCT_M1:  "< -10"  # кредитный портфель ↓ >10% за месяц
    QN9_PCT_M6:  "< -20"  # кредитный портфель ↓ >20% за полгода
    O2_PCT_M1:   "> 10"   # средства от банков ↑ >10% за месяц
    O2_PCT_M6:   "> 20"   # средства от банков ↑ >20% за полгода
    O1_PCT_M1:   "< -10"  # счета клиентов ↓ >10% за месяц
    O1_PCT_M6:   "< -20"  # счета клиентов ↓ >20% за полгода
  # Набор 3
  - A1_PCT_M6:   "> 50"   # денежные средства ↑ >50% за полгода
    QN9_PCT_M1:  "< -10"  # кредитный портфель ↓ >10% за месяц
    QN9_PCT_M6:  "< -20"  # кредитный портфель ↓ >20% за полгода
    QN15_PCT_M1: "< -10"  # капитал ↓ >10% за месяц
    QN15_PCT_M6: "< -20"  # капитал ↓ >20% за полгода
  # Набор 4
  - QN13_PCT_M1: "< -10"  # совокупные активы ↓ >10% за месяц
    QN13_PCT_M6: "< -20"  # совокупные активы ↓ >20% за полгода
    A1_PCT_M1:   "< -10"  # денежные средства ↓ >10% за месяц
    A1_PCT_M6:   "< -20"  # денежные средства ↓ >20% за полгода
    QN9_PCT_M1:  "< -10"  # кредитный портфель ↓ >10% за месяц
    QN9_PCT_M6:  "< -20"  # кредитный портфель ↓ >20% за полгода
    O1_PCT_M1:   "< -10"  # счета клиентов ↓ >10% за месяц
    O1_PCT_M6:   "< -20"  # счета клиентов ↓ >20% за полгода
